version: '2'

services:

  redux-hist:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .git:/redux-hist/.git
    encrypted_env_file: secret.env.encrypted
    cached: true
